.\" This Source Code Form is subject to the terms of the Mozilla Public"
.\" License, v. 2.0. If a copy of the MPL was not distributed with this"
.\" file, You can obtain one at http://mozilla.org/MPL/2.0/."
.\""
.TH HAKABANA-CLEAN 1 "2014" "Haka" Commands
.SH NAME
hakabana-clean \- Remove 'hakabana' index from elasticsearch server
.SH DESCRIPTION
This script uses curl to delete 'hakabana' index from elasticsearch server.
.SH SYNOPSIS
\fBhakabana-clean\fP <\fIelasticsearch-server[:port]\fP>
.SH SEE ALSO
\fIhaka\fR\|(1)
\fIhakabana\fR\|(1)
.SH AUTHORS
Team HAKA - Arkoon
.SH COPYRIGHT
Arkoon Network Security, OpenWide and Telecom ParisTech.
